# Generated by Django 3.2.9 on 2023-01-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20230102_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='libele',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
