# Generated by Django 3.2.9 on 2023-01-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_auto_20230124_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='corrections',
            field=models.BooleanField(default=False, help_text='À cocher si cette categorie possède des corrections'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='libele',
            field=models.CharField(default='Nom', help_text="Petit texte d'entête du tableau", max_length=200),
        ),
    ]
