# Generated by Django 3.2.9 on 2023-02-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=' ')),
                ('libele', models.CharField(default='Nom', help_text="Petit texte d'entête du tableau", max_length=200)),
                ('corrections', models.BooleanField(default=False, help_text='À cocher si cette categorie possède des corrections')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='chimie/')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chimie.categorie')),
            ],
        ),
    ]
