# Generated by Django 3.2.9 on 2023-02-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimie', '0002_alter_document_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='chimie/'),
        ),
    ]
