# Generated by Django 3.2.9 on 2023-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimie', '0003_alter_document_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fichier',
        ),
        migrations.AddField(
            model_name='document',
            name='fichiers',
            field=models.TextField(blank=True, help_text="chaque ligne représente un fichier au format 'fichier.pdf' "),
        ),
    ]
