# Generated by Django 3.2.9 on 2023-10-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimie', '0004_auto_20231022_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='corrections',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='libele',
        ),
        migrations.AddField(
            model_name='categorie',
            name='colonnes',
            field=models.PositiveIntegerField(default=1, help_text="Indiquer le nombre de colonne qu'il y aura (hors celle de numérotation)"),
        ),
        migrations.AddField(
            model_name='categorie',
            name='entetes',
            field=models.CharField(default='Nom', help_text="Les entêtes du tableau séparées par des '/' \n Ex: Nom/Fichier/Correction", max_length=200),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nombre_affichage',
            field=models.PositiveIntegerField(default=20, help_text="Corespond au nombre d'éléments qui seront affichés au chargement de la page"),
        ),
    ]
