# Generated by Django 3.2.9 on 2023-04-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=' ')),
                ('entetes', models.CharField(default='Nom', help_text="Les entêtes du tableau séparées par des '/' \n Ex: Nom/Fichier/Correction", max_length=200)),
                ('colonnes', models.PositiveIntegerField(default=1, help_text="Indiquer le nombre de colonne qu'il y aura (hors celle de numérotation)")),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fichiers', models.TextField(blank=True, help_text="chaque ligne représente un fichier au format 'fichier.pdf' ")),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physique.categorie')),
            ],
        ),
    ]
