# Generated by Django 3.2.9 on 2023-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nombre_affichage',
            field=models.PositiveIntegerField(default=20, help_text="Corespond au nombre d'éléments qui seront affichés au chargement de la page"),
        ),
    ]
