# Generated by Django 3.2.9 on 2023-01-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
