# Generated by Django 3.2.9 on 2023-08-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0002_categorie_nombre_affichage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telechargements_cette_semaine', models.PositiveIntegerField(default=0)),
                ('telechargements_global', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physique.categorie')),
            ],
        ),
    ]
