# Generated by Django 3.2.9 on 2023-08-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0003_statistiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiques',
            name='telechargements_semaine_derniere',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
