# Generated by Django 3.2.9 on 2023-01-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0004_categorie_libele'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='corrections',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='libele',
            field=models.CharField(default='Nom', max_length=200),
        ),
    ]
