# Generated by Django 3.2.9 on 2024-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0004_statistiques_telechargements_semaine_derniere'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
