# Generated by Django 3.2.9 on 2023-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0005_auto_20230102_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='libele',
            field=models.CharField(default='Nom', help_text="Petit texte d'entete du tableau", max_length=200),
        ),
    ]
