# Generated by Django 3.2.9 on 2023-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physique', '0007_auto_20230124_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(blank=True, help_text="Au format 'fichier.pdf' ", max_length=200),
        ),
    ]
